#!/data/data/com.termux/files/usr/bin/bash
FEX_DATA=/data/data/com.termux/files/home/Fex-Android/data/fex_data
source $FEX_DATA
cd /data/data/com.termux/files/home/Fex-Android
function start_ubuntu()
{
    echo kill
}
function uninstall()
{
    dialog --title "FEX-Android Uninstall" --yesno "Do you want uninstall Fex?" 10 50
    if [ $? == 0 ]; then
	rm -rf /data/data/com.termux/files/home/Fex-Android/
	rm /data/data/com.termux/files/usr/bin/fex
        exit 0
    else
        main_menu
    fi
}

function root_killall()
{
    sudo ps -ax | grep "[F]EXIn" | awk '{print $1}' | xargs sudo kill -9 > /dev/null 2>&1
    sudo ps -ax | grep "[p]ulseaudio" | awk '{print $1}' | xargs sudo kill -9 > /dev/null 2>&1
    sudo ps -ax | grep "[c]om.termux.x11.Loader" | awk '{print $1}' | xargs sudo kill -9 > /dev/null 2>&1
}
function root_kill()
{
    root_killall
    dialog --title "FEX-Android" --msgbox "All progress has been killed" 10 50
    main_menu
}

function _killall()
{
    ps -ax | grep "[p]root" | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
    ps -ax | grep "[F]EXIn" | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
    ps -ax | grep "[p]ulseaudio" | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
    ps -ax | grep "[c]om.termux.x11.Loader" | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
}

function _kill()
{
    _killall
    dialog --title "FEX-Android" --msgbox "All progress has been killed" 10 50
    main_menu
}
function write_env()
{
    printf "DRI3=$DRI3\nGL=$GL\nVK=$VK\nFEX=$FEX\nDBG=$DBG\nWINE=$WINE\nESYNC=$ESYNC\nSCR=$SCR\nsrc1=$src1\nsrc2=$src2\nsrc3=$src3\nsrc4=$src4\nsrc5=$src5\nsrc6=$src6\nver=$ver" >$FEX_DATA
    chmod 777 $FEX_DATA
}
function start_fex()
{
    if [[ $ESYNC == "Enabled" ]]; then
	export WINEESYNC=1
    fi
    if [[ $DRI3 == "Enabled" ]]; then
        export FEX_X87REDUCEDPRECISION=true
        echo "cmdstart='/opt/wine/$WINE/bin/wine64 explorer /desktop=shell,$SCR /opt/tfm.exe'" > start.sh
    else
        export MESA_VK_WSI_DEBUG=sw
        export FEX_X87REDUCEDPRECISION=true
        echo "cmdstart='/opt/wine/$WINE/bin/wine64 explorer /desktop=shell,$SCR /opt/tfm.exe'" > start.sh
    fi
    _killall
    if [[ $DBG == "Enabled" ]]; then
	clear
	echo -e "\e[32m[+] run Debug mode in Proot\e[0m"
        echo -e "\e[32m[+] type command exit to automatic kill session\e[0m"
	termux-x11 :1 > /dev/null 2>&1 &
	am start -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1 &
	./start-proot.sh
	_kill
	main_menu
    fi
    termux-x11 :1 > /dev/null 2>&1 &
    checkroot=$(sudo whoami)
    if [[ $checkroot == "root" ]]; then
	./start-chroot.sh > /dev/null 2>&1 &
	mode="chroot root detected"
    else
	export WINEDEBUG=-all
	./start-proot.sh > /dev/null 2>&1 &
	mode="proot non-root detected"
    fi
    am start -n com.termux.x11/com.termux.x11.MainActivity
    dialog --title "FEX-Android" --msgbox "Tap Ok to Stop Wine\nWine Version $WINE\nscreen Resolution $SCR\nTermux-X11 DRI3 $DRI3\nMode $mode Wine-Esync $ESYNC" 10 50
    if [[ $checkroot == "root" ]]; then
        root_kill
    else
        _kill
    fi
    main_menu
}
function config_fex()
{
    list=$(dialog --title "FEX-Android" --menu "FEX-Configuration" 20 70 25 \
	1 "DRI3    Enabled Termux-X11 DRI3                $DRI3" \
	2 "GL      Enabled OpenGL Thunk libs              $GL" \
	3 "Vulkan  Enabled Vulkan Thunk libs              $VK" \
	4 "FEX     Run FEX-Android when Termux startup    $FEX" \
	5 "DEBUG   Run Fex-emu with Wine Debug in proot   $DBG" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
        main_menu
    fi
    case $list in
    1)
	_dri3=$(dialog --title "FEX-Configuration" --menu "Do you want to Enabled/Disabled DRI3 feature?" \
		10 40 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
	case $_dri3 in
	1)
	    DRI3="Enabled"
	    write_env;;
	2)
	    DRI3="Disabled"
	    write_env;;
	esac
	config_fex
	;;
    2)
	_gl=$(dialog --title "FEX-Configuration" --menu "Do you want to Enabled/Disabled OpenGL feature?" \
		10 40 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
	case $_gl in
	1)
	    GL="Enabled"
	    write_env;;
	2)
	    GL="Disabled"
	    write_env;;
	esac
	config_fex
	;;
    3)
	_vk=$(dialog --title "FEX-Configuration" --menu "Do you want to Enabled/Disabled Vulkan feature?" \
		10 40 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
	case $_vk in
	1)
	    VK="Enabled"
	    echo '{"ThunksDB": {"Vulkan": 1}}' > ubuntu-fs64/root/.fex-emu/thunks.json
	    write_env;;
	2)
	    VK="Disabled"
	    echo '{"ThunksDB": {"Vulkan": 0}}' > ubuntu-fs64/root/.fex-emu/thunks.json
	    write_env;;
	esac
	config_fex
	;;
    4)
	_fex=$(dialog --title "FEX-Configuration" --menu "Do you want to Enabled/Disabled FEX feature?" \
		10 40 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
	case $_fex in
	1)
	    echo "fex" >~/.bashrc
	    FEX="Enabled"
            write_env;;
	2)
	    rm >~/.bashrc
	    FEX="Disabled"
            write_env;;
	esac
	config_fex;;
    5)
	_dbg=$(dialog --title "FEX-Configuration" --menu "Do you want to Enabled/Disabled debug mode?" \
                10 40 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
	case $_dbg in
	1)
	    DBG="Enabled"
	    write_env;;
	2)
	    DBG="Disabled"
	    write_env;;
	esac
	config_fex;;
    *)
	main_menu
	config_fex;;
    esac
    main_menu
}
function wine_scr()
{
    choice=$(dialog --radiolist "Screen Size" 20 40 25 \
	"1" "640x480" "$src1" \
	"2" "800x600" "$src2" \
	"3" "1024x768" "$src3" \
	"4" "1280x720" "$src4" \
	"5" "1600x900" "$src5" \
	"6" "1920x1080" "$src6" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
	main_menu
    fi
    case $choice in
    1)
	SCR="640x480";;
    2)
	SCR="800x600";;
    3)
	SCR="1024x768";;
    4)
	SCR="1280x720";;
    5)
	SCR="1600x900";;
    6)
	SCR="1920x1080";;
    esac
    write_env
    wine
}

function wine_csrc()
{
    width=$(dialog --inputbox "Width" 8 40 "" 2>&1 >/dev/tty)
    height=$(dialog --inputbox "Width" 8 40 "" 2>&1 >/dev/tty)
    SCR="$width""x""$height"
    write_env
    wine
}

function resetprefix()
{
    rm -rf ubuntu-fs64/root/.wine | dialog --infobox "removing files..." 10 50
    clear
	echo -e "\e[32m[+] Creating Wine Prefix\e[0m"
    echo "cmdstart='/opt/wine/$WINE/bin/wine64 wineboot -u'" >> start.sh
	./start-proot.sh
    dialog --title "Fex-Android $ver" --msgbox "$WINE has been set for Fex-Emu" 10 50
    main_menu
}

function wine_ver()
{
    _winever=$(dialog --menu "Select Wine version" 20 45 25 1 "wine-9.17-amd64 (Stable, Recommend)" 2 "wine-9.2-staging-tkg-amd64 (Unstable, Staging)" 3 "lutris-GE-Proton8-15-x86_64 (Unstable, Staging)" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
        wine;
    fi
    case $_winever in
    1)
	if [ -d ubuntu-fs64/opt/wine/wine-9.17-amd64 ]; then
	    WINE=wine-9.17-amd64
	    write_env
	    resetprefix
	    main_menu;
	else
	    dialog --yesno "Do you want download wine-9.17-amd64 from Kron4ek/Wine-Builds" 10 40
	    if [[ $? == 1 ]]; then
        	wine_ver;
    	    fi
	    clear
	    mkdir ubuntu-fs64/opt/wine/wine-9.17-amd64
	    WINE=wine-9.17-amd64
	    wget https://github.com/Kron4ek/Wine-Builds/releases/download/9.17/wine-9.17-amd64.tar.xz -O wine-9.17-amd64.tar.xz
	    echo -e "\e[32m[+] Completed Download $WINE ...\e[0m"
	    echo -e "\e[32m[+] Extracting Wine $WINE\e[0m"
	    tar -xf wine-9.17-amd64.tar.xz -C ubuntu-fs64/opt/wine
	    rm wine-9.17-amd64.tar.xz
            write_env
            resetprefix
            main_menu;
	fi
	;;
    2)
	if [ -d ubuntu-fs64/opt/wine/wine-9.2-staging-tkg-amd64 ]; then
            WINE=wine-9.2-staging-tkg-amd64
            write_env
            resetprefix
            main_menu;
	else
            dialog --yesno "Do you want download wine-9.2-staging-tkg-amd64 from Kron4ek/Wine-Builds" 10 40
            if [[ $? == 1 ]]; then
                wine_ver;
            fi
            clear
	        mkdir -p ubuntu-fs64/opt/wine/wine-9.2-staging-tkg-amd64
            wget https://github.com/Kron4ek/Wine-Builds/releases/download/9.2/wine-9.2-staging-tkg-amd64.tar.xz -O wine-9.2-staging-tkg-amd64.tar.xz
            WINE=wine-9.2-staging-tkg-amd64
            echo -e "\e[32m[+] Completed Download $WINE ...\e[0m"
            echo -e "\e[32m[+] Extracting Wine $WINE\e[0m"
            tar -xf wine-9.2-staging-tkg-amd64.tar.xz -C ubuntu-fs64/opt/wine
            rm wine-9.2-staging-tkg-amd64.tar.xz
            write_env
            resetprefix
            main_menu;
	fi
	;;
    3)
	if [ -d ubuntu-fs64/opt/wine/lutris-GE-Proton8-15-x86_64 ]; then
            WINE=lutris-GE-Proton8-15-x86_64
            write_env
            resetprefix
            main_menu;
        else
            dialog --yesno "Do you want download lutris-GE-Proton8-15-x86_64 from GloriousEggroll/wine-ge-custom" 10 40
            if [[ $? == 1 ]]; then
                wine_ver;
	    fi
            clear
	    mkdir -p ubuntu-fs64/opt/wine/lutris-GE-Proton8-15-x86_64
            wget https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-15/wine-lutris-GE-Proton8-15-x86_64.tar.xz -O wine-lutris-GE-Proton8-15-x86_64.tar.xz
	    wget https://github.com/AllPlatform/Fex-Android/releases/download/v1.3-update/prefix-wine-lutris-GE-Proton8-15-x86_64.tar.xz -O ubuntu-fs64/opt/wine/lutris-GE-Proton8-15-x86_64/wine.tar.xz
	    WINE=lutris-GE-Proton8-15-x86_64
	    echo -e "\e[32m[+] Completed Download $WINE ...\e[0m"
            echo -e "\e[32m[+] Extracting Wine $WINE\e[0m"
	    tar -xf wine-lutris-GE-Proton8-15-x86_64.tar.xz -C ubuntu-fs64/opt/wine
	    rm wine-lutris-GE-Proton8-15-x86_64.tar.xz
            write_env
            resetprefix
            main_menu;
	fi
	;;
    esac
    wine
}

function wineesync()
{
    _env=$(dialog --title "wine-esync" --menu "We do not recommend Enabled Wine esync" 10 45 25 1 "Enabled" 2 "Disabled" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
        wine;
    fi
    case $_env in
    1)
        write_env
	ESYNC=Enabled;;
    2)
	write_env
	ESYNC=Disabled;;
    esac
    wine
}

function wine()
{
    output=$(dialog --menu "FEX-Android Wine Screen $SCR" 20 45 25 1 "Screen Size" 2 "Custom Screen Size" 3 "reset Wine Prefix" 4 "Select Wine version" 5 "Wine-esync" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
	main_menu;
    fi
    case $output in
    1)
	wine_scr;;
    2)
	wine_csrc;;
    3)
	resetprefix;;
    4)
	wine_ver;;
    5)
	wineesync;;
    esac
    main_menu
}
function about_fex()
{
    dialog --title "FEX-Android Script ver $ver" --msgbox \
	" Termux script written by AkiraYuki\n\
	Fex-emu  https://github.com/FEX-Emu/FEX\n\
	Wine     https://gitlab.winehq.org/wine/wine\n\
	Mesa     https://gitlab.freedesktop.org/mesa\n\
	DXVK     https://github.com/doitsujin/dxvk\n\
	Termux   https://github.com/termux\n\
	Proot    https://github.com/proot-me" 30 65
    main_menu
}
function run_terminal()
{
    clear
    echo -e "\e[32m[+] run Terminal mode in Proot\e[0m"
    echo -e "\e[32m[+] type command  exit to automatic kill session\e[0m"
    echo "cmdstart='/bin/bash --login'" > start.sh
    ./start-proot.sh
    _kill
}
function main_menu()
{
    if [[ $WINE == "0" ]]; then
	wine_ver
    fi
    var=$(dialog --menu "FEX-Android $ver" 20 45 25 1 "Start FEX-Emu" 2 "Configure Fex" 3 "Wine" 4 "Run Terminal" 5 "Kill All" 6 "About" 7 "Uninstall" 8 "Exit" 2>&1 >/dev/tty)
    if [[ $? == 1 ]]; then
        exit 0
    fi
    case $var in
    1)
	start_fex;;
    2)
	config_fex;;
    3)
	wine;;
    4)
	run_terminal;;
    5)
	_kill;;
    6)
	about_fex;;
    7)
	uninstall;;
    8)
	exit 0;;
    esac
    exit 0
}
main_menu
